version: "3.6"

services:
  core:
    extends:
      file: ./deploy/docker-compose.yml
      service: core-service
    build:
      context: ./core-service
    volumes:
      - ./core-service:/app
    depends_on:
      - "database"
      - "web"
  auth:
    extends:
      file: ./deploy/docker-compose.yml
      service: auth-service
    build:
      context: ./auth-service
    volumes:
      - ./auth-service:/app
    depends_on:
      - "core"
  web:
    extends:
      file: ./deploy/docker-compose.yml
      service: web-service
    depends_on:
      - "rabbitmq"
  database:
    extends:
      file: ./deploy/docker-compose.yml
      service: database
    depends_on:
      - "rabbitmq"
  rabbitmq:
    extends:
      file: ./deploy/docker-compose.yml
      service: rabbitmq
