version: "3.6"
services:
  rabbitmq:

  database:
    depends_on:
      - rabbitmq

  web-service:
    depends_on:
      - database

  core-service:
    build: ./core-service
    volumes:
      - ./core-service:/app
    depends_on:
      - database

  auth-service:
    build: ./auth-service
    volumes:
      - ./auth-service:/app
    depends_on:
      - core-service
