#!/bin/bash
cp .env.example .env
cd ./auth-service
composer u --ignore-platform-reqs
cd ../core-service
composer u --ignore-platform-reqs
cd ../
sudo ss -lptn 'sport = :5432' -K
sudo docker-compose up -d --build
