#!/bin/bash
sudo docker rm -f $(sudo docker ps -a -q)
sudo docker volume rm $(sudo docker volume ls -q)
sudo docker rmi $(sudo docker images -a -q)
cd auth-service
rm -rf vendor
cd ../core-service
rm -rf vendor
cd ..
